In [ ]:
# MAGIC SQUARE


import numpy as np

val  = 3
magic_square = np.zeros((val,val), dtype=int)

incrementer = 1
rowindex = 0
colindex = val//2

while incrementer <= val**2:
    magic_square[rowindex, colindex] = incrementer
    incrementer +=1
    x = (rowindex-1) % val
    y = (colindex+1)% val
    if magic_square[x, y]:
        rowindex +=1
    else:
        rowindex = x
        colindex =  y

print(magic_square)

[[8 1 6]
 [3 5 7]
 [4 9 2]]


In [ ]:
import numpy as np
sudoku = []
print("For the blanks put 0")

for i in range(9):
    row = list(input("Don't give the spaces or columns while typing the elments in the row{} : -".format(i+1)))
    row = [int(i) for i in row]
    sudoku.append(row)
print(np.matrix(sudoku))


def possible(y,x,n):
    global sudoku
    for i in range(0,9):
        if sudoku[y][i] == n:
            return False
    for i in range(0,9):
        if sudoku[i][x] == n:
            return False
    box_y = (y//3)*3
    box_x = (x//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if sudoku[box_y+i][box_x+j] == n:
                return False
    return True
def solve():
    for y in range(0,9):
        for x in range(0,9):
            if sudoku[y][x] == 0:
                for n in range(1,10):
                    if possible(y,x,n):
                        sudoku[y][x] = n
                        solve()
                        sudoku[y][x] = 0
                return
    print(np.matrix(sudoku))
solve()

For the blanks put 0
Don't give the spaces or columns while typing the elments in the row1 : -600745000
Don't give the spaces or columns while typing the elments in the row2 : -050032400
Don't give the spaces or columns while typing the elments in the row3 : -480196703
Don't give the spaces or columns while typing the elments in the row4 : -514000962
Don't give the spaces or columns while typing the elments in the row5 : -007020180
Don't give the spaces or columns while typing the elments in the row6 : -820500004
Don't give the spaces or columns while typing the elments in the row7 : -000200000
Don't give the spaces or columns while typing the elments in the row8 : -206980030
Don't give the spaces or columns while typing the elments in the row9 : -000013800
[[6 0 0 7 4 5 0 0 0]
 [0 5 0 0 3 2 4 0 0]
 [4 8 0 1 9 6 7 0 3]
 [5 1 4 0 0 0 9 6 2]
 [0 0 7 0 2 0 1 8 0]
 [8 2 0 5 0 0 0 0 4]
 [0 0 0 2 0 0 0 0 0]
 [2 0 6 9 8 0 0 3 0]
 [0 0 0 0 1 3 8 0 0]]
[[6 9 3 7 4 5 2 1 8]
 [7 5 1 8 3 2 4 9 6]


In [3]:
player, opponent = 'x', 'o'

def isMovesLeft(board) :
    for i in range(3) :
        for j in range(3) :
            if (board[i][j] == '_') :
                return True
    return False
 
def evaluate(b) :
    for row in range(3) :    
        if (b[row][0] == b[row][1] and b[row][1] == b[row][2]) :       
            if (b[row][0] == player) :
                return 10
            elif (b[row][0] == opponent) :
                return -10
 
    for col in range(3) :
      
        if (b[0][col] == b[1][col] and b[1][col] == b[2][col]) :
         
            if (b[0][col] == player) :
                return 10
            elif (b[0][col] == opponent) :
                return -10
 
    if (b[0][0] == b[1][1] and b[1][1] == b[2][2]) :
     
        if (b[0][0] == player) :
            return 10
        elif (b[0][0] == opponent) :
            return -10
 
    if (b[0][2] == b[1][1] and b[1][1] == b[2][0]) :
     
        if (b[0][2] == player) :
            return 10
        elif (b[0][2] == opponent) :
            return -10
 
    return 0
"""
def print_matrix(matrix):
    for i in range(3):
        for j in range(3):
            if j == 3 - 1:
                print(matrix[i][j])
            else:
                print(matrix[i][j], end="   |   ")
        print('--------' * 3)

    print("\n")
"""
def minimax(board, isMax) :
    score = evaluate(board)
 
    if (score == 10) :
        return score
 
    if (score == -10) :
        return score
 
    if (isMovesLeft(board) == False) :
        return 0
 
    if (isMax) :    
        best = -1000
 
        for i in range(3) :        
            for j in range(3) :
                if (board[i][j]=='_') :
                    board[i][j] = player
                    best = max( best, minimax(board, not isMax) )
                    board[i][j] = '_'
        return best
    else :
        best = 1000
 
        for i in range(3) :        
            for j in range(3) :
              
                if (board[i][j] == '_') :
                 
                    board[i][j] = opponent
 
                    best = min(best, minimax(board, not isMax))
 
                    board[i][j] = '_'
        return best
    
def findBestMove(board) :
    bestVal = -1000
    bestMove = (-1, -1)
 
    for i in range(3) :    
        for j in range(3) :
            if (board[i][j] == '_') :
             
                board[i][j] = player
 
                moveVal = minimax(board, False)

 
                board[i][j] = '_'
 
                if (moveVal > bestVal) :               
                    bestMove = (i, j)
                    bestVal = moveVal
 
    print("The value of the best Move is :", bestVal)
    print()
    return bestMove

# Driver code
board = [
    [ 'o', '_', '_' ],
    [ '_', '_', 'x' ],
    [ '_', '_', '_' ]
]
 
bestMove = findBestMove(board)
 
print("The Optimal Move is :")
print("ROW:", bestMove[0], " COL:", bestMove[1])

The value of the best Move is : 10

The Optimal Move is :
ROW: 0  COL: 2
